# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0e4619d50fd2bc1bff2ad8a54912aa3b95ccdcf8d0088b7a186be8fbbb15a5c4e1f37b6691d007b42a01fc51b2a9378fe2c82eaa9cc38bd820b3f00cc3be694a

test:
  secret_key_base: 4a03e3457c4f9ee8a061d020211ea280751520aa8b3663e0865bd3da702b041314a7f5c553e34c449b349ddd1b93baede5cbde32ac140ed763cc2da65c634067

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
